# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 올뉴스
email: s23q@protonmail.com
author: "올뉴스"
logo: "./1.png"
lang: "ko"
description: "올뉴스"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://w9oi.github.io" # the base hostname & protocol for your site
timezone: Asia/Seoul
encoding: UTF-8

webmaster_verifications:
  google: ""

tracking:
  ga_id: "UA-xxxxxx-yy"

# Build settings
markdown: kramdown
kramdown:
  input: GFM

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

permalink: /7/:title

